<?php $this->layout('layout') ?>
<?php $this->start('title') ?>주문 상세 · 쇼핑몰 · <?= $this->e($site['site_name']) ?><?php $this->stop() ?>
<?php $this->start('nav_section') ?>shop<?php $this->stop() ?>
<?php $this->start('body_class') ?>yc-page yc-order-page<?php $this->stop() ?>
<?php $this->start('seo_meta') ?><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="<?= $this->asset('youngcart.css') ?>"><?php $this->stop() ?>
<?php $this->start('body') ?>
<?php $weekdayNames = ['일', '월', '화', '수', '목', '금', '토']; $weekdayDate = fn (int $timestamp): string => $this->date($timestamp) . ' (' . $weekdayNames[(int) $this->date($timestamp, 'w')] . ')'; ?>
<div class="yc-shop">
<?php $this->insert('_header') ?>
<div class="yc-page-heading"><div><p class="yc-kicker yc-order-number"><span data-order-number><?= $this->e($order['number']) ?></span><?php if ($order['payment_environment'] === 'test'): ?><span class="yc-test-badge">테스트 결제</span><?php endif ?><button class="yc-order-copy" type="button" data-copy-order-number aria-label="주문번호 복사">복사</button></p><h1 class="yc-title">주문 상세</h1></div><a class="yc-more" href="<?= $this->e($url) ?>/orders">주문 조회 <?= $this->icon('chevron-right', 17) ?></a></div>
<?php $this->insert('_feedback') ?>
<?php if (($pay_state ?? '') === 'success' || ($order_placed ?? false)): ?><div class="yc-feedback yc-feedback-success" role="status"><strong>주문이 정상적으로 접수되었습니다.</strong><span><?= ($order_placed ?? false) ? '입금 확인 후 주문이 진행됩니다.' : '결제가 완료되었습니다. 주문 내역을 확인해 주세요.' ?></span></div><?php endif ?>
<section class="yc-panel yc-order-current"><h2>현재 진행 상황</h2><div class="yc-order-current-row"><div class="yc-order-current-value"><span class="yc-status" data-status="<?= $this->e($order['status']) ?>"><?= $this->e($statuses[$order['status']]) ?></span><time><?= $this->e($weekdayDate((int) $current_status_at)) ?></time></div><a class="yc-more" href="#yc-order-history">진행 이력 보기 <?= $this->icon('chevron-right', 17) ?></a></div></section>
<div class="yc-commerce-grid"><div class="yc-checkout-sections">
<?php $this->insert('_order_detail') ?>
<section class="yc-panel yc-order-history" id="yc-order-history"><h2>진행 이력</h2><ol class="yc-order-timeline"><?php foreach ($order['history'] as $event): ?><li><div><strong><?= $this->e($statuses[$event['status']]) ?></strong><?php if ($event['status'] === 'cancelled' && str_starts_with((string) $event['actor'], 'user:') && $event['note'] !== ''): ?><p class="muted"><?= $this->e($event['note']) ?></p><?php endif ?></div><time><?= $this->e($weekdayDate((int) $event['created_at'])) ?></time></li><?php endforeach ?></ol>
<?php if ($order['status'] === 'paid' || ($order['status'] === 'pending' && !$pay_in_progress && !($order['payment_method'] === 'virtual_account' && isset($order['payment']['virtual_account'])))): ?><details class="yc-cancel"<?= ($cancel_attempted ?? false) ? ' open' : '' ?>><summary><?= $order['status'] === 'paid' ? '상품 준비 전 주문 취소' : '주문 취소' ?></summary><p>상품 준비 전까지 주문 전체를 취소할 수 있습니다. 사유를 선택해 주세요.<?php if ($order['status'] === 'paid' && $is_pg): ?> 결제사에 남은 결제액을 전액 취소한 뒤 주문이 취소됩니다.<?php elseif ($order['status'] === 'paid' && !$is_pg): ?> 입금액 반환은 상점에서 별도로 처리합니다.<?php endif ?></p><form class="yc-form-stack" method="post" action="<?= $this->e($url) ?>/order/cancel"><input type="hidden" name="csrf_token" value="<?= $this->e($csrf_token) ?>"><input type="hidden" name="number" value="<?= $this->e($order['number']) ?>"><?php $this->insert('_cancel_reason_fields', ['cancel_reason_required' => true]) ?><button class="yc-button yc-button-outline yc-button-block" type="submit">전체 주문 취소하기</button></form></details><?php endif ?></section>
</div><aside class="yc-order-summary"><h2><?= $order['status'] === 'cancelled' ? '취소된 주문 금액' : '주문 금액' ?></h2><?php $this->insert('_totals', ['quote' => $order]) ?><div class="yc-order-notice"><strong>주문 접수 안내</strong><p><?= nl2br($this->e($order['order_notice'])) ?></p><?php if ($order['payment_method'] === ''): ?><p>온라인 결제 내역이 없는 주문입니다.</p><?php endif ?></div>
<?php if ($pay_in_progress && $order['status'] === 'pending'): ?><div class="yc-order-notice"><strong>결제 확인 중</strong><p>결제 결과를 확인하는 중입니다. 잠시 후 이 화면을 다시 열어 주세요.</p></div>
<?php elseif ($pay_url !== null): ?><div class="yc-order-notice"><strong>결제 대기</strong><p><?= $pay_state === 'closed' ? '결제창이 닫혔습니다. ' : ($pay_state === 'failed' ? '결제 결과를 확인하지 못했습니다. 중복 결제를 피하려면 결제 내역을 확인하거나 상점에 문의해 주세요. ' : '') ?>결제 기한 <?= $this->e($weekdayDate((int) $order['pay_by'])) ?></p><a class="yc-button yc-button-primary yc-button-block" href="<?= $this->e($pay_url) ?>">결제하기</a></div>
<?php elseif ($pay_expired): ?><div class="yc-order-notice"><strong>결제 대기</strong><p>결제 기한이 지났습니다. 주문을 다시 접수해 주세요.</p></div><?php endif ?>
<?php if ($order['payment_method'] === 'manual_transfer' && $order['status'] === 'pending'): ?><div class="yc-order-notice"><strong>입금 안내</strong><p><?= $this->e(($order['payment']['bank'] ?? '') . ' ' . ($order['payment']['account'] ?? '') . ' (예금주 ' . ($order['payment']['holder'] ?? '') . ')') ?></p><p>입금자명 <?= $this->e(($order['payment']['depositor'] ?? '') !== '' ? $order['payment']['depositor'] : $order['buyer_name']) ?> · 입금 기한 <?= $this->e($weekdayDate((int) $order['pay_by'])) ?></p></div><?php endif ?>
<?php if ($order['status'] === 'cancelled' && !$is_pg && (int) $order['paid_amount'] > (int) $order['refunded_amount']): ?><div class="yc-order-notice"><strong>입금액 반환 안내</strong><p>주문은 취소되었습니다. 입금액 반환은 상점에서 별도로 처리합니다. 반환 내역은 상점에 문의해 주세요.</p></div><?php endif ?>
<?php if ($order['payment_method'] === 'virtual_account' && is_array($order['payment']['virtual_account'] ?? null)): $account = $order['payment']['virtual_account']; $due = \DateTimeImmutable::createFromFormat('!YmdHis', (string) ($account['due_date'] ?? '') . (string) ($account['due_time'] ?? ''), new \DateTimeZone('Asia/Seoul')); $dueAt = $due !== false ? $due->getTimestamp() : 0; ?><div class="yc-order-notice"><strong><?= $order['status'] === 'paid' ? '가상계좌 입금 완료' : '가상계좌 입금 안내' ?></strong><p>은행: <?= $this->e($account['bank'] ?? '') ?></p><p>가상계좌: <?= $this->e($account['account'] ?? '') ?></p><p>예금주: <?= $this->e($account['holder'] ?? '') ?></p><p>입금 기한: <?= $this->e($weekdayDate($dueAt)) ?></p><?php if ($order['status'] !== 'paid'): ?><p>입금 확인 후 주문 상태가 자동으로 갱신됩니다.</p><?php endif ?></div><?php endif ?>
<?php if ((int) $order['paid_at'] > 0): $card = $order['payment']['card'] ?? []; $hasCardDetails = is_array($card) && array_filter($card, static fn ($value): bool => $value !== '' && $value !== null && $value !== false) !== []; $receiptUrl = $order['payment_provider'] === 'inicis' && ($order['payment']['tid'] ?? '') !== '' ? 'https://iniweb.inicis.com/receipt/iniReceipt.jsp?noTid=' . rawurlencode((string) $order['payment']['tid']) : ''; $fullyRefunded = (int) $order['paid_amount'] > 0 && (int) $order['refunded_amount'] >= (int) $order['paid_amount']; ?><div class="yc-order-notice yc-order-notice-payment"><strong><?= $fullyRefunded ? '결제 취소' : '결제 완료' ?></strong>
<dl class="yc-order-payment-facts">
<div><dt>결제 수단</dt><dd><?= $this->e($method_labels[$order['payment_method']] ?? $order['payment_method']) ?></dd></div>
<div class="yc-order-payment-amount"><dt><?= $order['payment_method'] === 'virtual_account' ? '입금액' : '결제 금액' ?></dt><dd><?= number_format((int) $order['paid_amount']) ?>원</dd></div>
<div><dt><?= $order['payment_method'] === 'virtual_account' ? '입금일' : '결제 일시' ?></dt><dd><?= $this->e($weekdayDate((int) $order['paid_at'])) ?></dd></div>
</dl><?php if ((int) $order['refunded_amount'] > 0): ?><p>환불액: <?= number_format((int) $order['refunded_amount']) ?>원</p><?php endif ?>
<?php if ($hasCardDetails): $cardName = $order['payment_provider'] === 'toss' ? \GnuCms\Payment\TossGateway::cardIssuerName((string) ($card['name'] ?? '')) : (string) ($card['name'] ?? ''); ?><dl class="yc-payment-details">
<?php if ($cardName !== ''): ?><div><dt>카드사</dt><dd><?= $this->e($cardName) ?><?= ($card['last_four'] ?? '') !== '' ? ' · 끝번호 ' . $this->e($card['last_four']) : '' ?></dd></div><?php endif ?>
<?php if (isset($card['quota']) && is_int($card['quota'])): ?><div><dt>할부</dt><dd><?= $card['quota'] === 0 ? '일시불' : $card['quota'] . '개월' ?><?= !empty($card['interest_free']) ? ' · 무이자' : '' ?></dd></div><?php endif ?>
<?php if (($card['approval_number'] ?? '') !== ''): ?><div><dt>승인번호</dt><dd><?= $this->e($card['approval_number']) ?></dd></div><?php endif ?>
</dl><?php endif ?>
<?php if ($receiptUrl !== ''): ?><a class="yc-button yc-button-outline yc-receipt-link" href="<?= $this->e($receiptUrl) ?>" target="_blank" rel="noopener noreferrer">영수증 확인 <?= $this->icon('external', 14) ?></a><small class="yc-receipt-help">이니시스 영수증 조회 화면에서 구매자명과 결제 금액을 확인합니다.</small><?php endif ?></div><?php endif ?>
<a class="yc-button yc-button-primary yc-button-block" href="<?= $this->e($url) ?>">계속 쇼핑하기</a></aside></div>
</div>
<?php $this->stop() ?>
<?php $this->start('scripts') ?><script src="<?= $this->asset('youngcart.js') ?>" defer></script><?php $this->stop() ?>
