<?php if (in_array($order['status'], ['shipped', 'completed'], true)): ?>
<details class="yc-panel"<?= $errors !== [] && ($input['action'] ?? '') === 'request-return' ? ' open' : '' ?>><summary>반품 요청 등록</summary><p class="yc-help">전화 등으로 접수한 주문 전체 반품을 등록합니다.</p>
<form class="yc-form-stack" method="post" action="<?= $this->e($admin_url) ?>/orders/detail"><input type="hidden" name="csrf_token" value="<?= $this->e($csrf_token) ?>"><input type="hidden" name="id" value="<?= (int) $order['id'] ?>"><input type="hidden" name="action" value="request-return">
<?php $this->insert('_return_reason_fields') ?><button class="btn btn-outline" type="submit">반품 요청 등록</button></form></details>
<?php elseif ($order['status'] === 'returning'): $returnRemaining = max(0, (int) $order['paid_amount'] - (int) $order['refunded_amount']); ?>
<section class="yc-panel"><h2>반품 처리</h2><p><?= $this->e($order['payment']['return']['reason'] ?? '') ?></p><p class="yc-help">상품을 돌려받은 뒤 주문 전체 반품을 완료합니다. 남은 환불액 <?= number_format($returnRemaining) ?>원.</p>
<form class="yc-form-stack" method="post" action="<?= $this->e($admin_url) ?>/orders/detail"><input type="hidden" name="csrf_token" value="<?= $this->e($csrf_token) ?>"><input type="hidden" name="id" value="<?= (int) $order['id'] ?>"><input type="hidden" name="action" value="complete-return">
<label class="label toggle-row"><input class="checkbox checkbox-sm" type="checkbox" name="return_received" value="1" required<?= ($input['return_received'] ?? '') === '1' ? ' checked' : '' ?>> 반품 상품을 돌려받았습니다</label>
<?php if (!$is_pg && $returnRemaining > 0): ?><label class="label toggle-row"><input class="checkbox checkbox-sm" type="checkbox" name="manual_refund_confirmed" value="1" required<?= ($input['manual_refund_confirmed'] ?? '') === '1' ? ' checked' : '' ?>> 실제 입금액 반환을 완료했습니다</label><?php endif ?>
<label class="label toggle-row"><input class="checkbox checkbox-sm" type="checkbox" name="return_restock" value="1"<?= ($input['return_restock'] ?? '') === '1' ? ' checked' : '' ?>> 재판매가 가능한 상품이므로 재고 복원</label>
<button class="btn btn-primary" type="submit">반품 완료·환불</button></form>
<details class="yc-cancel"><summary>반품 요청 종료</summary><form class="yc-form-stack" method="post" action="<?= $this->e($admin_url) ?>/orders/detail"><input type="hidden" name="csrf_token" value="<?= $this->e($csrf_token) ?>"><input type="hidden" name="id" value="<?= (int) $order['id'] ?>"><input type="hidden" name="action" value="close-return"><label class="yc-field"><span>종료 사유 <small>회원에게 표시</small></span><input class="input input-bordered" name="reason" maxlength="400" required></label><button class="btn btn-outline" type="submit">요청 종료</button></form></details></section>
<?php elseif ($order['status'] === 'returned'): ?><section class="yc-panel"><h2>반품 완료</h2><p class="yc-help"><?= !empty($order['payment']['return']['restocked']) ? '상품 재고를 복원했습니다.' : '상품 재고는 복원하지 않았습니다.' ?></p></section><?php endif ?>
